-sv

../rtl/branch_resolver.sv
../rtl/btb.sv
../rtl/decoder.sv
../rtl/decoder_full.sv
../rtl/division.sv
../rtl/execution.sv
../rtl/floating_alu.sv
../rtl/flush_controller.sv
../rtl/gshare.sv
../rtl/icache.sv
../rtl/idecode.sv
../rtl/ifetch.sv
../rtl/int_alu.sv
../rtl/issue.sv
../rtl/load_store_unit.sv
../rtl/multiply.sv
../rtl/predictor.sv
../rtl/processor_top.sv
../rtl/ras.sv
../rtl/register_file.sv
../rtl/rob.sv
../rtl/module_top.sv
../rtl/enum.sv
../rtl/csr_registers.sv
../rtl/rr.sv
../rtl/rat.sv
../rtl/free_list.sv

../rtl/fifo_dual_ported.sv
../rtl/fifo_duth.sv
../rtl/fifo_flush.sv
../rtl/fifo_overflow.sv
../rtl/fifo_initialized.sv
../rtl/vga_controller.sv
../rtl/sram.sv
../rtl/lru.sv
../rtl/lru2.sv
../rtl/lrumore.sv
../rtl/onehot_detect.sv
../rtl/and_or_mux.sv
../rtl/arbiter.sv
../rtl/eb_buff_generic.sv
../rtl/eb_one_slot.sv
../rtl/eb_two_slot.sv
../rtl/wait_buffer.sv
../rtl/data_cache.sv
../rtl/data_operation.sv
../rtl/ld_st_buffer.sv
../rtl/main_memory.sv
../rtl/structs.sv

../rtl/vector/dispatch/*.sv
../rtl/vector/memory_interface/*.sv
../rtl/vector/vector_lane/*.sv
../rtl/vector/vector_top/*.sv

../rtl/reservation_station.sv
../rtl/general/*.sv